<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="1" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-03-23T10:44:53 IST" name="inetBankingV1" finished-at="2021-03-23T10:45:12 IST" duration-ms="18927">
    <groups>
    </groups>
    <test started-at="2021-03-23T10:44:53 IST" name="BankingApp ChromeTest" finished-at="2021-03-23T10:45:12 IST" duration-ms="18927">
      <class name="com.inetbanking.testcases.TC_DeleteCustTest_006">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:44:53 IST" name="setup" finished-at="2021-03-23T10:45:00 IST" duration-ms="6315" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[edge]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="login()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:00 IST" name="login" finished-at="2021-03-23T10:45:02 IST" duration-ms="2627" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:02 IST" name="endResult" finished-at="2021-03-23T10:45:02 IST" duration-ms="4" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=login status=SUCCESS method=TC_DeleteCustTest_006.login()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method signature="addCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:02 IST" name="addCust" finished-at="2021-03-23T10:45:07 IST" depends-on-methods="com.inetbanking.testcases.TC_DeleteCustTest_006.login" duration-ms="4132" status="FAIL">
          <exception class="org.openqa.selenium.UnhandledAlertException">
            <message>
              <![CDATA[unexpected alert open: {Alert text : Customer could not be added !!}
  (Session info: MicrosoftEdge=89.0.774.57): Customer could not be added !!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-HLGI9113', ip: '192.168.228.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.edge.EdgeDriver
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 89.0.774.57, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:58779}, msedge: {msedgedriverVersion: 89.0.774.45 (bb55f48a0d369c..., userDataDir: C:\Users\vinayak\AppData\Lo...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 49cb8590056dea789a768fc2ebd1c143
*** Element info: {Using=xpath, value=//p[contains(text(),'Successfully!!!')]}]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.UnhandledAlertException: unexpected alert open: {Alert text : Customer could not be added !!}
  (Session info: MicrosoftEdge=89.0.774.57): Customer could not be added !!
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'LAPTOP-HLGI9113', ip: '192.168.228.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '11.0.10'
Driver info: org.openqa.selenium.edge.EdgeDriver
Capabilities {acceptInsecureCerts: false, browserName: msedge, browserVersion: 89.0.774.57, javascriptEnabled: true, ms:edgeOptions: {debuggerAddress: localhost:58779}, msedge: {msedgedriverVersion: 89.0.774.45 (bb55f48a0d369c..., userDataDir: C:\Users\vinayak\AppData\Lo...}, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: WINDOWS, platformName: WINDOWS, proxy: Proxy(), setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 49cb8590056dea789a768fc2ebd1c143
*** Element info: {Using=xpath, value=//p[contains(text(),'Successfully!!!')]}
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:120)
at org.openqa.selenium.remote.http.W3CHttpResponseCodec.decode(W3CHttpResponseCodec.java:49)
at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:552)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:323)
at org.openqa.selenium.remote.RemoteWebDriver.findElementByXPath(RemoteWebDriver.java:428)
at org.openqa.selenium.By$ByXPath.findElement(By.java:353)
at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:315)
at org.openqa.selenium.support.pagefactory.DefaultElementLocator.findElement(DefaultElementLocator.java:69)
at org.openqa.selenium.support.pagefactory.internal.LocatingElementHandler.invoke(LocatingElementHandler.java:38)
at com.sun.proxy.$Proxy16.isDisplayed(Unknown Source)
at com.inetbanking.pageobjects.NewCustomerPage.succTxt(NewCustomerPage.java:154)
at com.inetbanking.testcases.TC_DeleteCustTest_006.addCust(TC_DeleteCustTest_006.java:43)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.UnhandledAlertException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addCust -->
        <test-method is-config="true" signature="endResult(org.testng.ITestResult)[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:07 IST" name="endResult" finished-at="2021-03-23T10:45:08 IST" duration-ms="1028" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=addCust status=FAILURE method=TC_DeleteCustTest_006.addCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endResult -->
        <test-method signature="editCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:08 IST" name="editCust" finished-at="2021-03-23T10:45:08 IST" depends-on-methods="com.inetbanking.testcases.TC_DeleteCustTest_006.addCust, com.inetbanking.testcases.TC_DeleteCustTest_006.login" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_DeleteCustTest_006.editCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_DeleteCustTest_006.editCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- editCust -->
        <test-method signature="deleteCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:08 IST" name="deleteCust" finished-at="2021-03-23T10:45:08 IST" depends-on-methods="com.inetbanking.testcases.TC_DeleteCustTest_006.addCust, com.inetbanking.testcases.TC_DeleteCustTest_006.editCust, com.inetbanking.testcases.TC_DeleteCustTest_006.login" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_DeleteCustTest_006.deleteCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_DeleteCustTest_006.deleteCust()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteCust -->
        <test-method signature="logout()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:08 IST" name="logout" finished-at="2021-03-23T10:45:08 IST" depends-on-methods="com.inetbanking.testcases.TC_DeleteCustTest_006.addCust, com.inetbanking.testcases.TC_DeleteCustTest_006.editCust, com.inetbanking.testcases.TC_DeleteCustTest_006.deleteCust, com.inetbanking.testcases.TC_DeleteCustTest_006.login" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TC_DeleteCustTest_006.logout()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TC_DeleteCustTest_006.logout()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logout -->
        <test-method is-config="true" signature="teardown()[pri:0, instance:com.inetbanking.testcases.TC_DeleteCustTest_006@61001b64]" started-at="2021-03-23T10:45:08 IST" name="teardown" finished-at="2021-03-23T10:45:12 IST" duration-ms="4000" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- com.inetbanking.testcases.TC_DeleteCustTest_006 -->
    </test> <!-- BankingApp ChromeTest -->
  </suite> <!-- inetBankingV1 -->
</testng-results>
